services:
  libreelec-image-injector:
    build: .
    privileged: true
    network_mode: none
    read_only: true
    tmpfs:
      - /tmp
    working_dir: /${WORKDIR:-work}
    environment:
      IMAGE: ${IMAGE:-}
    volumes:
      - ./images/source:/${WORKDIR:-work}/images/source:ro
      - ./images/injected:/${WORKDIR:-work}/images/injected:rw
      - ./config:/${WORKDIR:-work}/config:ro
      - ./scripts:/${WORKDIR:-work}/scripts:ro
    command: ./scripts/inject-config.sh
